### PR TITLE
[CHK-1793] static folder & npg styling

### PR DESCRIPTION
**Pull request by mmoio**
Provide styling to the npg payment form and adds a static folder to be served directly by parcel in development. 

#### List of Changes
 - npg styling used in the iFrameCardForm component
 - serve static folder in development
 - copy static folder content to dist during build
 - Most static files (privacypolicy, ot, robots.txt and  p/response.html) moved to static folder

#### Motivation and Context

- The npg payment from requires an external css file and the name must be known at build time.
- Serving the static folder in development makes possible to se file changes on page reload.
- The privacypolicy page has been moved to the new static folder, this makes possible to share styling and fonts between privacypolicy and npg/style.css.
-  ot, robots.txt and  p/response.html adn privacypolicy files have been moved to the new static folder, so to use a single copy command in the build script.

#### How Has This Been Tested?

Visual testing using the [checkout-be-mock](https://github.com/pagopa/pagopa-checkout-be-mock/tree/feat/1789) branch: `feat/1789`

#### Screenshots (if appropriate):
image

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by infantesimone** [comment]
The name of new Nexi payment gateway is not `xpay` but `npg`

**Comment by mmoio** [comment]
> The name of new Nexi payment gateway is not `xpay` but `npg`

Should I replace every instance of `xpay` with `npg`?

**Comment by infantesimone** [comment]
> > The name of new Nexi payment gateway is not `xpay` but `npg`
> 
> Should I replace every instance of `xpay` with `npg`?

yep

**Review by vito80ba — APPROVED** [review]
LGTM

**Pull request merged**
