### PR TITLE
[CHK-1826] fix card form duplication

### PR DESCRIPTION
**Pull request by mmoio**
#### List of Changes

- payment choice page uses location assign to navigate to card data page 
- payment check page removes `beforeunload` listener before navigating back to card data page
- payment check page uses location replace to navigate back to card data page 

#### Motivation and Context

Use location replace or assign instead of router-dom navigate so to
cause a window reload and cleaning the window from frames
loaded by previous npg sdk builds

#### How Has This Been Tested?

Visual testing

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ciuffagianluca** [comment]
Hi @mmoio ,
this solution solve the issue between the PaymentCheckPage and IFrameCardPage.
But the bug is still present between PaymentChoicePage and IFrameCardPage. In that case too the invocation is replicated n times if you navigate n times between the 2 pages.

**Review by ciuffagianluca — COMMENTED** [review]
Hi @mmoio ,
this solution solve the issue between the PaymentCheckPage and IFrameCardPage.
But the bug is still present between PaymentChoicePage and IFrameCardPage. In that case too the invocation is replicated n times if you navigate n times between the 2 pages.

**Comment by mmoio** [comment]
> Hi @mmoio , this solution solve the issue between the PaymentCheckPage and IFrameCardPage. But the bug is still present between PaymentChoicePage and IFrameCardPage. In that case too the invocation is replicated n times if you navigate n times between the 2 pages.

Hi, I've updated the PaymentChoicePage to use location for navigation to IFrameCardPage

**Review by ciuffagianluca — APPROVED** [review]
Well done! 🚀

**Review by vito80ba — APPROVED** [review]

**Pull request merged**
