### PR TITLE
feat: brand convertion for pgs

### PR DESCRIPTION
**Pull request by infantesimone**
#### List of Changes

- brand conversion for pgs

#### Motivation and Context

The goal of this PR is to convert the brand compute with `card-validator` lib with the enum managed by authorization API.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ciuffagianluca** [comment]
Code seems to be ok, but something is broken in the build step of the pipeline

**Comment by stratoivandiluccio** [comment]
Code seems ok. But i can't understand why do we have a new yarn.lock file without adding or removing dependencies from the package.json file.

**Comment by stratoivandiluccio** [comment]
I have also noticed some unit test failures, that's why the build step is broken I think:

image

**Comment by infantesimone** [comment]
> I have also noticed some unit test failures, that's why the build step is broken I think:
> 
> image

correct, there were some bugs on the develop branch that were fixed on this PR https://github.com/pagopa/pagopa-checkout-fe/pull/185

**Review by stratoivandiluccio — APPROVED** [review]

**Pull request merged**
